### ISSUE TITLE
🔴 [BUG] Hovering effect is not so effective and active page can't be recognised easily

### ISSUE THREAD

**Issue by Nincompup** [amanrajrana/RobustKey-PasswordGenerator#43] opened 2023-10-12 06:39 UTC
### Description of the bug

The hovering effect on the navbar link is not so efficient and the user can't get easily which page is currently active.

### Please add screenshots (if applicable)

https://github.com/amanrajrana/RobustKey-PasswordGenerator/assets/114563503/8c584768-e942-4278-8853-62a6fa2b3c08

**Comment by Nincompup** [comment] 2023-10-12 06:41
Hey @amanrajrana could you assign this issue to me? So I can fix this bug.

**Comment by amanrajrana** [comment] 2023-10-12 12:48
@Nincompup assigned to you.

Happy coding

**Comment by amoghpujari** [comment] 2023-10-12 15:28
Hii @amanrajrana can I contribute to this issue?

**Comment by amanrajrana** [comment] 2023-10-12 16:35
@amoghpujari Yes, Go ahead

**Comment by amanrajrana** [comment] 2023-10-13 03:45
The issue is not Resolved.

**Comment by hmadhsan** [comment] 2023-10-13 10:47
Hi, Aman can you assign this issue to me if it is still not resolved?

**Comment by amanrajrana** [comment] 2023-10-14 16:14
Fixed in #63

**Closed by amanrajrana** 2023-10-14 16:14 UTC
Labels: bug, good first issue, hactoberfest
